name: amt
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8.5
  - pip=20.3
  - cudatoolkit=11.3
  - pytorch=1.11.0
  - torchvision=0.12.0
  - numpy=1.21.5
  - pip:
    - opencv-python==4.1.2.30
    - imageio==2.19.3
    - omegaconf==2.3.0
    - Pillow==9.4.0
    - tqdm==4.64.1
    - wandb==0.12.21