# Special Config
resume_from_checkpoint: /remote-home/lzj/Open-Sora-Plan/results/pretrained
# Model config
in_channels: 3
out_channels: 3
hidden_size: 128
z_channels: 4
ch_mult:
  - 1
  - 2
  - 4
  - 4
num_res_block: 2
attn_resolutions: []
dropout: 0.0
resolution: 64
attn_type: vanilla3D
use_linear_attn: false
embed_dim: 4
time_compress: 2
logvar_init: 0.0
kl_weight: 0.000001
pixelloss_weight: 1
perceptual_weight: 1
# Trainer config
per_device_train_batch_size: 2
gradient_accumulation_steps: 1
learning_rate: 0.00001
weight_decay: 0.0
lr_scheduler_type: cosine
max_grad_norm: 1.0
save_strategy: steps
save_total_limit: 5
logging_steps: 5
save_steps: 100
output_dir: results/causalvae
bf16: true
report_to: tensorboard
dataloader_num_workers: 10
# dataset config
data_path: "/remote-home1/dataset/UCF-101"
video_num_frames: 9
sample_rate: 1