CUDA_VISIBLE_DEVICES=0 python examples/rec_imvi_vae.py \
    --ae_path "../../Open-Sora-Plan/CausalVAEModel_4x8x8/" \
    --video_path origin_tiger.mp4 \
    --rec_path rec.mp4 \
    --device cuda \
    --sample_rate 1 \
    --num_frames 65 \
    --resolution 512 \
    --crop_size 512 \
    --ae CausalVAEModel_4x8x8 \
    --enable_tiling