CUDA_VISIBLE_DEVICES=1 python opensora/sample/sample_t2v.py \
    --model_path 512_10node_bs2_lr2e-5_4img/checkpoint-94000/model \
    --version 65x512x512 \
    --image_size 512 \
    --cache_dir "./cache_dir" \
    --text_encoder_name DeepFloyd/t5-v1_1-xxl \
    --text_prompt examples/prompt_list_0.txt \
    --ae CausalVAEModel_4x8x8 \
    --ae_path "/dxyl_data02/CausalVAEModel_4x8x8/" \
    --save_img_path "./sample_videos_94k_7.5_150s" \
    --fps 24 \
    --guidance_scale 7.5 \
    --num_sampling_steps 150 \
    --enable_tiling
