aa: null
amp: false
apex_amp: false
aug_splits: 0
batch_size: 32
bn_eps: null
bn_momentum: null
bn_tf: false
channels_last: false
clip_grad: null
color_jitter: 0.4
cooldown_epochs: 10
crop_pct: null
cutmix: 0.0
cutmix_minmax: null
decay_epochs: 30
decay_rate: 0.1
dist_bn: ''
drop: 0.0
drop_block: null
drop_connect: null
drop_path: null
dropout_rate: 0.0
epochs: 200
eval_metric: top1
expand_dim: 3072
gp: null
hflip: 0.5
hidden_dim: 768
img_size: null
initial_checkpoint: ''
interpolation: ''
jsd: false
kv_dim: 768
local_rank: 0
log_interval: 50
lr: 0.01
lr_cycle_limit: 1
lr_cycle_mul: 1.0
lr_noise: null
lr_noise_pct: 0.67
lr_noise_std: 1.0
max_history: 10
max_img_size:
- 3
- 512
- 512
max_token_dropout_rate: 0.8
max_token_lim: 2048
mean: null
min_lr: 1.0e-05
min_token_dropout_rate: 0.2
mixup: 0.0
mixup_mode: batch
mixup_off_epoch: 0
mixup_prob: 1.0
mixup_switch_prob: 0.5
model: NaViT
model_ema: false
model_ema_decay: 0.9998
model_ema_force_cpu: false
momentum: 0.9
native_amp: false
no_aug: false
no_prefetcher: false
no_resume_opt: false
num_classes: 1000
num_gpu: 1
num_heads: 16
num_layers: 12
opt: sgd
opt_betas: null
opt_eps: null
output: ''
patch_size: 16
patience_epochs: 10
pin_mem: false
pos_emb_type: learned
pretrained: false
q_dim: 768
ratio:
- 0.75
- 1.3333333333333333
recount: 1
recovery_interval: 0
remode: const
repeated_aug: false
reprob: 0.0
resplit: false
resume: ''
save_images: false
scale:
- 0.08
- 1.0
sched: step
seed: 42
smoothing: 0.1
split_bn: false
start_epoch: null
start_step: 0
std: null
sync_bn: false
task: cls
temp: 1
token_dropout_temp: 0.1
train_interpolation: random
tta: 0
use_multi_epochs_loader: false
validation_batch_size_multiplier: 1
vflip: 0.0
warmup_epochs: 3
warmup_lr: 0.0001
weight_decay: 0.0001
workers: 4
