CUDA_VISIBLE_DEVICES=3 python opensora/sample/sample_t2v.py \
    --model_path /storage/ongoing/new/7.19anyres/Open-Sora-Plan/bs1x8x16_1x720p_lr1e-4_snr5_noioff0.02_ema9999_sparse1d16_dit_l_122_rope_mt5xxl_mj_fromhw480p/checkpoint-4000/model_ema \
    --version 65x512x512 \
    --num_frames 1 \
    --height 720 \
    --width 1280 \
    --cache_dir "../cache_dir" \
    --text_encoder_name google/mt5-xxl \
    --text_prompt examples/prompt_list_1.txt \
    --ae CausalVAEModel_D4_4x8x8 \
    --ae_path "/storage/dataset/488dim4_plus" \
    --save_img_path "sample_images_sparse1d16_dit_9k" \
    --fps 24 \
    --guidance_scale 4.5 \
    --num_sampling_steps 20 \
    --enable_tiling \
    --max_sequence_length 512 \
    --sample_method DPMSolverMultistep \
    --model_type dit