CUDA_VISIBLE_DEVICES=7 python opensora/sample/sample_t2v.py \
    --model_path /storage/dataset/hw29/model_ema \
    --version 65x512x512 \
    --num_frames 29 \
    --height 480 \
    --width 640 \
    --cache_dir "../cache_dir" \
    --text_encoder_name google/mt5-xxl \
    --text_prompt examples/prompt_list_1.txt \
    --ae CausalVAEModel_4x8x8 \
    --ae_path "/storage/dataset/test140k" \
    --save_img_path "sample_video_29x480p_hw_pndm_ema_fp32" \
    --fps 24 \
    --guidance_scale 5.0 \
    --num_sampling_steps 50 \
    --enable_tiling \
    --max_sequence_length 512 \
    --sample_method PNDM \
    --model_type dit