
CUDA_VISIBLE_DEVICES=0 torchrun --nnodes=1 --nproc_per_node 1 --master_port 29513 \
    -m opensora.sample.sample_t2v \
    --model_path /storage/ongoing/new/7.19anyres/Open-Sora-Plan/bs32x8x1_anyx93x640x640_fps16_lr1e-5_snr5_ema9999_sparse1d4_dit_l_mt5xxl_vpred_zerosnr/checkpoint-144000/model_ema \
    --version v1_2 \
    --num_frames 29 \
    --height 160 \
    --width 320 \
    --cache_dir "../cache_dir" \
    --text_encoder_name_1 "/storage/ongoing/new/Open-Sora-Plan/cache_dir/mt5-xxl" \
    --text_prompt examples/dense_output_cn.txt \
    --ae WFVAEModel_D8_4x8x8 \
    --ae_path "/storage/lcm/Causal-Video-VAE/results/WFVAE_DISTILL_FORMAL" \
    --save_img_path "./gyy_dense_output_m0.9_cfg7.5_seed3_cn_refine_v2v" \
    --fps 18 \
    --guidance_scale 7.5 \
    --num_sampling_steps 50 \
    --max_sequence_length 512 \
    --sample_method EulerAncestralDiscrete \
    --motion_score 0.9 \
    --seed 3 \
    --num_samples_per_prompt 2 \
    --prediction_type "v_prediction" \
    --rescale_betas_zero_snr \
    --caption_refiner "/storage/ongoing/refine_model/llama3_1_instruct_lora/llama3_8B_lora_merged_cn" \
    --save_memory