CUDA_VISIBLE_DEVICES=6 python opensora/sample/sample_t2v.py \
    --model_path "/storage/1.1model/hw_65/model" \
    --num_frames 65 \
    --height 512 \
    --width 512 \
    --cache_dir "/storage/cache_dir" \
    --text_encoder_name DeepFloyd/t5-v1_1-xxl \
    --text_prompt examples/prompt_list_0.txt \
    --ae CausalVAEModel_4x8x8 \
    --ae_path "/storage/CausalVAEModel_4x8x8" \
    --save_img_path "./sample_video_65x512x512" \
    --fps 24 \
    --guidance_scale 7.5 \
    --num_sampling_steps 50 \
    --enable_tiling \
    --sample_method PNDM \