CUDA_VISIBLE_DEVICES=6 python opensora/sample/sample_inpaint.py \
    --model_path /storage/gyy/hw/Open-Sora-Plan/inpaint_125x480p_bs1_lr1e-5_snr5_noioff0.02_new_mask \
    --num_frames 125 \
    --height 480 \
    --width 640 \
    --cache_dir "../cache_dir" \
    --text_encoder_name google/mt5-xxl \
    --ae CausalVAEModel_D4_4x8x8 \
    --ae_path "/storage/dataset/test140k" \
    --save_img_path "./sample_inpaint_125x480p_bs1_lr1e-5_snr5_noioff0.02_new_mask" \
    --fps 24 \
    --guidance_scale 3.0 \
    --num_sampling_steps 50 \
    --enable_tiling \
    --max_sequence_length 512 \
    --sample_method PNDM \
    --model_3d \
    --validation_dir "./validation_dir"