
CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 torchrun --nnodes=1 --nproc_per_node 8 --master_port 29512 \
    -m opensora.sample.sample \
    --model_path /storage/ongoing/9.29/mmdit/Open-Sora-Plan/any1x216x384_min160_lr2e-5_bs2048__mmdit8b_vpred_vaed32fp16/checkpoint-5000/model_ema \
    --version v1_5 \
    --num_frames 1 \
    --height 208 \
    --width 208 \
    --cache_dir "../cache_dir" \
    --text_encoder_name_1 "/storage/cache_dir/t5-v1_1-xl" \
    --text_encoder_name_2 "/storage/cache_dir/CLIP-ViT-bigG-14-laion2B-39B-b160k" \
    --text_prompt examples/sora_refine.txt \
    --ae WFVAEModel_D32_4x8x8 \
    --ae_path "/storage/lcm/WF-VAE/results/latent32_formal" \
    --save_img_path "./test_sample_v1_5" \
    --fps 18 \
    --guidance_scale 7.5 \
    --num_sampling_steps 24 \
    --max_sequence_length 512 \
    --sample_method EulerAncestralDiscrete \
    --seed 1234 \
    --num_samples_per_prompt 1 \
    --prediction_type "v_prediction" \
    --rescale_betas_zero_snr