CUDA_VISIBLE_DEVICES=6 python opensora/sample/sample_t2v.py \
    --model_path /storage/ongoing/new/7.19anyres/Open-Sora-Plan/bs1x8x32_max480p_lr1e-4_snr5_noioff0.02_ema9999_udit122_rope_fp32_mt5xxl_sam_humanimg/checkpoint-5500/model_ema \
    --version 65x512x512 \
    --num_frames 1 \
    --height 480 \
    --width 640 \
    --cache_dir "../cache_dir" \
    --text_encoder_name google/mt5-xxl \
    --text_prompt examples/prompt_list_1.txt \
    --ae CausalVAEModel_4x8x8 \
    --ae_path "/storage/dataset/test140k" \
    --save_img_path "sample_image_fp32_cfg2.5_step20_max480p_pos_neg" \
    --fps 24 \
    --guidance_scale 4.5 \
    --num_sampling_steps 20 \
    --enable_tiling \
    --max_sequence_length 512 \
    --sample_method PNDM \
    --model_type udit