CUDA_VISIBLE_DEVICES=0 python opensora/sample/sample_inpaint.py \
    --model_path "/storage/1.1model/hw_65/model/diffusion_pytorch_model.safetensors" \
    --num_frames 65 \
    --height 512 \
    --width 512 \
    --cache_dir "/storage/cache_dir" \
    --text_encoder_name DeepFloyd/t5-v1_1-xxl \
    --text_prompt examples/prompt_list_0.txt \
    --ae CausalVAEModel_4x8x8 \
    --ae_path "/storage/CausalVAEModel_4x8x8" \
    --validation_dir "/storage/gyy/hw/Open-Sora-Plan/test_dir" \
    --output_dir "./test_sample" \
    --guidance_scale 7.5 \
    --num_sampling_steps 50 \
    --enable_tiling \
    --sample_method PNDM \