
CUDA_VISIBLE_DEVICES=0 torchrun --nnodes=1 --nproc_per_node 1 --master_port 29512 \
    -m opensora.sample.sample \
    --model_path /storage/ongoing/9.29/mmdit/Open-Sora-Plan/any1x384x384_min288x384_lr1e-4_bs2048_mmdit2b_prenorm_rf_fp32vae888_wd0.1_gn0.3_notout_noskip/checkpoint-2000/model_ema \
    --version v1_5 \
    --num_frames 1 \
    --height 384 \
    --width 384 \
    --cache_dir "../cache_dir" \
    --text_encoder_name_1 "/storage/cache_dir/t5-v1_1-xl" \
    --text_encoder_name_2 "/storage/cache_dir/CLIP-ViT-bigG-14-laion2B-39B-b160k" \
    --text_prompt examples/sora_refine.txt \
    --ae WFVAEModel_D32_8x8x8 \
    --ae_path "/storage/lcm/WF-VAE/results/formal_888_lbstd" \
    --save_img_path "./test_1x384x384_v1_5_2bprenorm_s28_ckpt2k_rf_wd_gn_noskip" \
    --fps 18 \
    --guidance_scale 7.0 \
    --num_sampling_steps 28 \
    --max_sequence_length 512 \
    --sample_method FlowMatchEulerDiscrete \
    --seed 1234 \
    --num_samples_per_prompt 1 \
    --prediction_type "v_prediction" \
    --v1_5_scheduler