# mask processor args
min_clear_ratio: 0.0
max_clear_ratio: 1.0 
dilate_kernel_size: 31
min_clear_ratio_hw: 0.2
max_clear_ratio_hw: 0.8

# mask_type_ratio_dict_video
mask_type_ratio_dict_video:
  # temporal-level
  t2iv: 0
  i2v: 3
  transition: 3
  continuation: 0
  clear: 0
  random_temporal: 0
  # spatial-level
  semantic: 1
  dilate: 1
  bbox: 1
  random_spatial: 1
  # outpainting
  outpaint_random_spatial: 0
  outpaint_semantic: 0
  outpaint_bbox: 0
  # mixed
  i2v_outpaint_semantic: 0

mask_type_ratio_dict_image:
  # temporal-level
  t2iv: 0
  clear: 0
  # spatial-level
  semantic: 0
  dilate: 0
  bbox: 0
  random_spatial: 0
  # outpainting
  outpaint_random_spatial: 0
  outpaint_semantic: 0
  outpaint_bbox: 0 